parent_dir = "exp/abalone/realtabformer"
real_data_path = "data/repo/abalone/"
seed = 0
device = "cuda"

[model_params]
version = "0.0.2.3.0"

[model_params.meta]
target_batch_size = 512
frac_max_data = 5000
checkpoints_dir = "rtf_checkpoints"
samples_save_dir = "rtf_samples"

[model_params.train]
model_type = "tabular"
batch_size = 128
epochs = 200
train_size = 1
random_state = 1029
early_stopping_patience = 0

[model_params.train.gpt_config]
n_layer = 6

[model_params.train.training_args_kwargs]
logging_steps = 100
save_steps = 100
eval_steps = 100
save_total_limit = 1


[model_params.fit]
qt_max = 0.05
qt_interval = 100
qt_interval_unique = 100
n_critic = 5
num_bootstrap = 500
sensitivity_max_col_nums = 5
use_ks = false
full_sensitivity = false
frac = 0.15
sensitivity_orig_frac_multiple = 4
orig_samples_rounds = 5


[model_params.sample]
gen_batch = 128

[sample]
seed = 0
num_samples = 21600
