parent_dir = "exp/gesture/realtabformer"
real_data_path = "data/repo/gesture/"


[model_params.meta]
target_batch_size = 64


[model_params.train]
batch_size = 32
numeric_precision = 6
numeric_max_len = 10